name = "meg-operations"
compatibility_date = "2026-08-04"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "meg-operations"
database_id = "13bad6c0-ee9f-41bb-9b22-c488ce34ccc1"

[vars]
PUBLIC_ORIGINS = "https://taizhou.jinxiliu.com"
OPS_ORIGINS = "https://megops.jinxiliu.com"
CF_ACCESS_TEAM_DOMAIN = "wandering-shape-ee6e"
CF_ACCESS_AUD = "f2999dc863741c6bb77b5793cc1b9f8d74ef2dcc8eae7837629b608df7130ae9"
LOCAL_DEV = "false"
